# 
# ===============================
# Server Properties
#=https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.server
# ===============================
spring.application.name=bytedesk
application.title=https://www.weiyuai.cn
application.version=0.7.3
server.port=9003

# ===============================
#=freemarker
# ===============================
spring.freemarker.template-loader-path=classpath:/templates/ftl/
# spring.freemarker.template-loader-path=classpath:/templates/ftl/, \
#     classpath:/bytedesk-module-forum/templates/ftl/, \
#     classpath:/bytedesk-module-voc/templates/ftl/
spring.freemarker.suffix=.ftl
# \u4EC5\u9002\u7528\u4E8E\u6D4B\u8BD5\u9636\u6BB5\uFF0C\u7EBF\u4E0A\u6CE8\u91CA\u6389
spring.freemarker.cache=false
spring.freemarker.charset=UTF-8
spring.freemarker.content-type=text/html
spring.freemarker.expose-request-attributes=true
spring.freemarker.expose-session-attributes=true

# ===============================
#=profiles
# \u6CE8\u610F\uFF1A\u5207\u6362\u4E0D\u540Cprofiles\u65F6\uFF0C\u9700\u8981\u540C\u6B65\u4FEE\u6539pom.xml\u5207\u6362driver\u9A71\u52A8
# ===============================
# dev
spring.profiles.active=dev
# spring.profiles.active=local
# saas 
# spring.profiles.active=prod

# TODO: split profiles
# spring.config.import=\
# application-dev-ai.properties,\
# application-dev-db.properties,\
# application-dev-redis.properties
